#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afloeser.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Afloeser_koder")]
	public partial class DataClass_afloeserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAfloeserBrugere(AfloeserBrugere instance);
    partial void UpdateAfloeserBrugere(AfloeserBrugere instance);
    partial void DeleteAfloeserBrugere(AfloeserBrugere instance);
    #endregion
		
		public DataClass_afloeserDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Afloeser_koderConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClass_afloeserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClass_afloeserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClass_afloeserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClass_afloeserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AfloeserAdgang> AfloeserAdgangs
		{
			get
			{
				return this.GetTable<AfloeserAdgang>();
			}
		}
		
		public System.Data.Linq.Table<AfloeserBrugere> AfloeserBrugeres
		{
			get
			{
				return this.GetTable<AfloeserBrugere>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AfloeserAdgang")]
	public partial class AfloeserAdgang
	{
		
		private int _MedarbejderID;
		
		private string _ADBrugerNavn;
		
		private string _Fornavn;
		
		private string _Efternavn;
		
		private string _Mail;
		
		private string _Tlfnr;
		
		private string _StillingBetegnelse;
		
		private string _ArbejdsstedNavn;
		
		private string _ArbejdsstedGade;
		
		private string _ArbejdsstedPostnr;
		
		private string _ArbejdstedBy;
		
		private string _LOSOrganisationsenhed;
		
		private string _LOSOrganisationID;
		
		private string _Omraede;
		
		private string _OmraedeID;
		
		public AfloeserAdgang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedarbejderID", DbType="Int NOT NULL")]
		public int MedarbejderID
		{
			get
			{
				return this._MedarbejderID;
			}
			set
			{
				if ((this._MedarbejderID != value))
				{
					this._MedarbejderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADBrugerNavn", DbType="VarChar(50)")]
		public string ADBrugerNavn
		{
			get
			{
				return this._ADBrugerNavn;
			}
			set
			{
				if ((this._ADBrugerNavn != value))
				{
					this._ADBrugerNavn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="VarChar(50)")]
		public string Fornavn
		{
			get
			{
				return this._Fornavn;
			}
			set
			{
				if ((this._Fornavn != value))
				{
					this._Fornavn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efternavn", DbType="VarChar(50)")]
		public string Efternavn
		{
			get
			{
				return this._Efternavn;
			}
			set
			{
				if ((this._Efternavn != value))
				{
					this._Efternavn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tlfnr", DbType="VarChar(50)")]
		public string Tlfnr
		{
			get
			{
				return this._Tlfnr;
			}
			set
			{
				if ((this._Tlfnr != value))
				{
					this._Tlfnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StillingBetegnelse", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StillingBetegnelse
		{
			get
			{
				return this._StillingBetegnelse;
			}
			set
			{
				if ((this._StillingBetegnelse != value))
				{
					this._StillingBetegnelse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArbejdsstedNavn", DbType="VarChar(255)")]
		public string ArbejdsstedNavn
		{
			get
			{
				return this._ArbejdsstedNavn;
			}
			set
			{
				if ((this._ArbejdsstedNavn != value))
				{
					this._ArbejdsstedNavn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArbejdsstedGade", DbType="VarChar(50)")]
		public string ArbejdsstedGade
		{
			get
			{
				return this._ArbejdsstedGade;
			}
			set
			{
				if ((this._ArbejdsstedGade != value))
				{
					this._ArbejdsstedGade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArbejdsstedPostnr", DbType="VarChar(50)")]
		public string ArbejdsstedPostnr
		{
			get
			{
				return this._ArbejdsstedPostnr;
			}
			set
			{
				if ((this._ArbejdsstedPostnr != value))
				{
					this._ArbejdsstedPostnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArbejdstedBy", DbType="VarChar(50)")]
		public string ArbejdstedBy
		{
			get
			{
				return this._ArbejdstedBy;
			}
			set
			{
				if ((this._ArbejdstedBy != value))
				{
					this._ArbejdstedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSOrganisationsenhed", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string LOSOrganisationsenhed
		{
			get
			{
				return this._LOSOrganisationsenhed;
			}
			set
			{
				if ((this._LOSOrganisationsenhed != value))
				{
					this._LOSOrganisationsenhed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSOrganisationID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LOSOrganisationID
		{
			get
			{
				return this._LOSOrganisationID;
			}
			set
			{
				if ((this._LOSOrganisationID != value))
				{
					this._LOSOrganisationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Omraede", DbType="VarChar(50)")]
		public string Omraede
		{
			get
			{
				return this._Omraede;
			}
			set
			{
				if ((this._Omraede != value))
				{
					this._Omraede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OmraedeID", DbType="VarChar(50)")]
		public string OmraedeID
		{
			get
			{
				return this._OmraedeID;
			}
			set
			{
				if ((this._OmraedeID != value))
				{
					this._OmraedeID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AfloeserBrugere")]
	public partial class AfloeserBrugere : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Navn;
		
		private string _Kategori;
		
		private System.DateTime _StartDato;
		
		private System.DateTime _SlutDato;
		
		private string _CPR;
		
		private string _Opretter;
		
		private System.Nullable<bool> _Deleted;
		
		private string _DeletedBy;
		
		private System.Nullable<System.DateTime> _DeletedDateTime;
		
		private string _TempCode_username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNavnChanging(string value);
    partial void OnNavnChanged();
    partial void OnKategoriChanging(string value);
    partial void OnKategoriChanged();
    partial void OnStartDatoChanging(System.DateTime value);
    partial void OnStartDatoChanged();
    partial void OnSlutDatoChanging(System.DateTime value);
    partial void OnSlutDatoChanged();
    partial void OnCPRChanging(string value);
    partial void OnCPRChanged();
    partial void OnOpretterChanging(string value);
    partial void OnOpretterChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    partial void OnDeletedByChanging(string value);
    partial void OnDeletedByChanged();
    partial void OnDeletedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedDateTimeChanged();
    partial void OnTempCode_usernameChanging(string value);
    partial void OnTempCode_usernameChanged();
    #endregion
		
		public AfloeserBrugere()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Navn", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Navn
		{
			get
			{
				return this._Navn;
			}
			set
			{
				if ((this._Navn != value))
				{
					this.OnNavnChanging(value);
					this.SendPropertyChanging();
					this._Navn = value;
					this.SendPropertyChanged("Navn");
					this.OnNavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Kategori
		{
			get
			{
				return this._Kategori;
			}
			set
			{
				if ((this._Kategori != value))
				{
					this.OnKategoriChanging(value);
					this.SendPropertyChanging();
					this._Kategori = value;
					this.SendPropertyChanged("Kategori");
					this.OnKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDato", DbType="DateTime NOT NULL")]
		public System.DateTime StartDato
		{
			get
			{
				return this._StartDato;
			}
			set
			{
				if ((this._StartDato != value))
				{
					this.OnStartDatoChanging(value);
					this.SendPropertyChanging();
					this._StartDato = value;
					this.SendPropertyChanged("StartDato");
					this.OnStartDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlutDato", DbType="DateTime NOT NULL")]
		public System.DateTime SlutDato
		{
			get
			{
				return this._SlutDato;
			}
			set
			{
				if ((this._SlutDato != value))
				{
					this.OnSlutDatoChanging(value);
					this.SendPropertyChanging();
					this._SlutDato = value;
					this.SendPropertyChanged("SlutDato");
					this.OnSlutDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPR", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string CPR
		{
			get
			{
				return this._CPR;
			}
			set
			{
				if ((this._CPR != value))
				{
					this.OnCPRChanging(value);
					this.SendPropertyChanging();
					this._CPR = value;
					this.SendPropertyChanged("CPR");
					this.OnCPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opretter", DbType="VarChar(250)")]
		public string Opretter
		{
			get
			{
				return this._Opretter;
			}
			set
			{
				if ((this._Opretter != value))
				{
					this.OnOpretterChanging(value);
					this.SendPropertyChanging();
					this._Opretter = value;
					this.SendPropertyChanged("Opretter");
					this.OnOpretterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="NVarChar(50)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedDateTime
		{
			get
			{
				return this._DeletedDateTime;
			}
			set
			{
				if ((this._DeletedDateTime != value))
				{
					this.OnDeletedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DeletedDateTime = value;
					this.SendPropertyChanged("DeletedDateTime");
					this.OnDeletedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempCode_username", DbType="NVarChar(50)")]
		public string TempCode_username
		{
			get
			{
				return this._TempCode_username;
			}
			set
			{
				if ((this._TempCode_username != value))
				{
					this.OnTempCode_usernameChanging(value);
					this.SendPropertyChanging();
					this._TempCode_username = value;
					this.SendPropertyChanged("TempCode_username");
					this.OnTempCode_usernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
